name: beakerx
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - beakerx
  - zookeeper-c
  - pip:
    - https://github.com/jupyterhub/jupyter-server-proxy/archive/master.zip
    - marathon
    - requests_toolbelt
    - pandas
